 
version: "3"
services:
  server:
    restart: always
    image: madeofpendletonwool/postfix
    environment:
      - SMTP_SERVER=smtp.office365.com
      - SMTP_USERNAME=send_email@email.com
      - SMTP_PASSWORD=mysecret
      - SERVER_HOSTNAME=send_email.email.com
      - SEND_ADDRESS=send_email@email.com
      - MESSAGE_SIZE_LIMIT=25000000
    ports:
      - "25:25"
